### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ThisTestUser** [BluSpring/MCP-Modificator#1]
First, thanks for creating this! It's really nice to have a script that automatically fixes ModCoderPack.
Here are some issues I found:
* Because different versions of Minecraft require different versions of the libraries to decompile it, you should refresh MCPConfig every time, to avoid grabbing the wrong version of the library.
* If you are decompiling MC 1.15.2, you should use ForgeFlower 1.5.380.40 instead of 1.5.380.44.
* You didn't check what version of the MCP mappings (fields, methods, params) to get.

**Comment by BluSpring** [comment]
Ah shoot, sorry for the late reply oops, I don't go on GitHub that often.
Alright, I'm gonna set these up now, thanks :D

**Comment by ThisTestUser** [comment]
Just a note that the latest MCPConfig has the ClientApplyPatches working now.

**Comment by BluSpring** [comment]
Fixed in the latest version (v1.0.1) :D
(still got Gradle issues though :V)
